import IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiСотрудникиEController from '../i-i-s-avtomatizaciya-ucheta-zayavok-v-i-t-kompanii-сотрудники-e';

var IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiСотрудникиENewController = IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiСотрудникиEController;
export default IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiСотрудникиENewController;
