import IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiЖивотныеEController from '../i-i-s-avtomatizaciya-ucheta-zayavok-v-i-t-kompanii-животные-e';

var IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiЖивотныеENewController = IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiЖивотныеEController;
export default IISAvtomatizaciya_ucheta_zayavok_v_IT_kompaniiЖивотныеENewController;
