//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Животные.
    /// </summary>
    // *** Start programmer edit section *** (Животные CustomAttributes)

    // *** End programmer edit section *** (Животные CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЖивотныеE", new string[] {
            "НомерЖивотного as \'Номер животного\'",
            "КодВида as \'Код вида\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ТабличНомер as \'Таблич номер\'"}, Hidden=new string[] {
            "Сотрудники.ТабличНомер"})]
    [AssociatedDetailViewAttribute("ЖивотныеE", "Сведения", "СведенияE", true, "", "Сведения", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЖивотныеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТабличНомер")]
    [View("ЖивотныеL", new string[] {
            "НомерЖивотного as \'Номер животного\'",
            "КодВида as \'Код вида\'",
            "Сотрудники.ТабличНомер as \'Таблич номер\'"})]
    public class Животные : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЖивотного;
        
        private int fКодВида;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сотрудники fСотрудники;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения fСведения;
        
        // *** Start programmer edit section *** (Животные CustomMembers)

        // *** End programmer edit section *** (Животные CustomMembers)

        
        /// <summary>
        /// КодВида.
        /// </summary>
        // *** Start programmer edit section *** (Животные.КодВида CustomAttributes)

        // *** End programmer edit section *** (Животные.КодВида CustomAttributes)
        [NotNull()]
        public virtual int КодВида
        {
            get
            {
                // *** Start programmer edit section *** (Животные.КодВида Get start)

                // *** End programmer edit section *** (Животные.КодВида Get start)
                int result = this.fКодВида;
                // *** Start programmer edit section *** (Животные.КодВида Get end)

                // *** End programmer edit section *** (Животные.КодВида Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.КодВида Set start)

                // *** End programmer edit section *** (Животные.КодВида Set start)
                this.fКодВида = value;
                // *** Start programmer edit section *** (Животные.КодВида Set end)

                // *** End programmer edit section *** (Животные.КодВида Set end)
            }
        }
        
        /// <summary>
        /// НомерЖивотного.
        /// </summary>
        // *** Start programmer edit section *** (Животные.НомерЖивотного CustomAttributes)

        // *** End programmer edit section *** (Животные.НомерЖивотного CustomAttributes)
        [NotNull()]
        public virtual int НомерЖивотного
        {
            get
            {
                // *** Start programmer edit section *** (Животные.НомерЖивотного Get start)

                // *** End programmer edit section *** (Животные.НомерЖивотного Get start)
                int result = this.fНомерЖивотного;
                // *** Start programmer edit section *** (Животные.НомерЖивотного Get end)

                // *** End programmer edit section *** (Животные.НомерЖивотного Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.НомерЖивотного Set start)

                // *** End programmer edit section *** (Животные.НомерЖивотного Set start)
                this.fНомерЖивотного = value;
                // *** Start programmer edit section *** (Животные.НомерЖивотного Set end)

                // *** End programmer edit section *** (Животные.НомерЖивотного Set end)
            }
        }
        
        /// <summary>
        /// Животные.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Животные.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Сотрудники Get start)

                // *** End programmer edit section *** (Животные.Сотрудники Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Животные.Сотрудники Get end)

                // *** End programmer edit section *** (Животные.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Сотрудники Set start)

                // *** End programmer edit section *** (Животные.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Животные.Сотрудники Set end)

                // *** End programmer edit section *** (Животные.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Животные.
        /// </summary>
        // *** Start programmer edit section *** (Животные.Сведения CustomAttributes)

        // *** End programmer edit section *** (Животные.Сведения CustomAttributes)
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения Сведения
        {
            get
            {
                // *** Start programmer edit section *** (Животные.Сведения Get start)

                // *** End programmer edit section *** (Животные.Сведения Get start)
                if ((this.fСведения == null))
                {
                    this.fСведения = new IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения(this);
                }
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения result = this.fСведения;
                // *** Start programmer edit section *** (Животные.Сведения Get end)

                // *** End programmer edit section *** (Животные.Сведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Животные.Сведения Set start)

                // *** End programmer edit section *** (Животные.Сведения Set start)
                this.fСведения = value;
                // *** Start programmer edit section *** (Животные.Сведения Set end)

                // *** End programmer edit section *** (Животные.Сведения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЖивотныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖивотныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖивотныеE", typeof(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные));
                }
            }
            
            /// <summary>
            /// "ЖивотныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЖивотныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЖивотныеL", typeof(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные));
                }
            }
        }
    }
}
