//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сведения.
    /// </summary>
    // *** Start programmer edit section *** (Сведения CustomAttributes)

    // *** End programmer edit section *** (Сведения CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СведенияE", new string[] {
            "Код as \'Код\'",
            "Клетки as \'Клетки\'",
            "Клетки.ТипКлетки as \'Тип клетки\'",
            "Корма as \'Корма\'",
            "Корма.ТипКорма as \'Тип корма\'",
            "Вид as \'Вид\'",
            "Вид.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Клетки.ТипКлетки",
            "Корма.ТипКорма",
            "Вид.Наименование"})]
    [MasterViewDefineAttribute("СведенияE", "Клетки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипКлетки")]
    [MasterViewDefineAttribute("СведенияE", "Корма", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ТипКорма")]
    [MasterViewDefineAttribute("СведенияE", "Вид", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class Сведения : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Клетки fКлетки;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Корма fКорма;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Вид fВид;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные fЖивотные;
        
        // *** Start programmer edit section *** (Сведения CustomMembers)

        // *** End programmer edit section *** (Сведения CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Код CustomAttributes)

        // *** End programmer edit section *** (Сведения.Код CustomAttributes)
        [NotNull()]
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Код Get start)

                // *** End programmer edit section *** (Сведения.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Сведения.Код Get end)

                // *** End programmer edit section *** (Сведения.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Код Set start)

                // *** End programmer edit section *** (Сведения.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Сведения.Код Set end)

                // *** End programmer edit section *** (Сведения.Код Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Вид CustomAttributes)

        // *** End programmer edit section *** (Сведения.Вид CustomAttributes)
        [PropertyStorage(new string[] {
                "Вид"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Вид Вид
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Вид Get start)

                // *** End programmer edit section *** (Сведения.Вид Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Вид result = this.fВид;
                // *** Start programmer edit section *** (Сведения.Вид Get end)

                // *** End programmer edit section *** (Сведения.Вид Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Вид Set start)

                // *** End programmer edit section *** (Сведения.Вид Set start)
                this.fВид = value;
                // *** Start programmer edit section *** (Сведения.Вид Set end)

                // *** End programmer edit section *** (Сведения.Вид Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Клетки CustomAttributes)

        // *** End programmer edit section *** (Сведения.Клетки CustomAttributes)
        [PropertyStorage(new string[] {
                "Клетки"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Клетки Клетки
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Клетки Get start)

                // *** End programmer edit section *** (Сведения.Клетки Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Клетки result = this.fКлетки;
                // *** Start programmer edit section *** (Сведения.Клетки Get end)

                // *** End programmer edit section *** (Сведения.Клетки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Клетки Set start)

                // *** End programmer edit section *** (Сведения.Клетки Set start)
                this.fКлетки = value;
                // *** Start programmer edit section *** (Сведения.Клетки Set end)

                // *** End programmer edit section *** (Сведения.Клетки Set end)
            }
        }
        
        /// <summary>
        /// Сведения.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Корма CustomAttributes)

        // *** End programmer edit section *** (Сведения.Корма CustomAttributes)
        [PropertyStorage(new string[] {
                "Корма"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Корма Корма
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Корма Get start)

                // *** End programmer edit section *** (Сведения.Корма Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Корма result = this.fКорма;
                // *** Start programmer edit section *** (Сведения.Корма Get end)

                // *** End programmer edit section *** (Сведения.Корма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Корма Set start)

                // *** End programmer edit section *** (Сведения.Корма Set start)
                this.fКорма = value;
                // *** Start programmer edit section *** (Сведения.Корма Set end)

                // *** End programmer edit section *** (Сведения.Корма Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные.
        /// </summary>
        // *** Start programmer edit section *** (Сведения.Животные CustomAttributes)

        // *** End programmer edit section *** (Сведения.Животные CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Животные"})]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные Животные
        {
            get
            {
                // *** Start programmer edit section *** (Сведения.Животные Get start)

                // *** End programmer edit section *** (Сведения.Животные Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные result = this.fЖивотные;
                // *** Start programmer edit section *** (Сведения.Животные Get end)

                // *** End programmer edit section *** (Сведения.Животные Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сведения.Животные Set start)

                // *** End programmer edit section *** (Сведения.Животные Set start)
                this.fЖивотные = value;
                // *** Start programmer edit section *** (Сведения.Животные Set end)

                // *** End programmer edit section *** (Сведения.Животные Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СведенияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СведенияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СведенияE", typeof(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сведения));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Сведения.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСведения CustomAttributes)
    public class DetailArrayOfСведения : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения members)

        // *** End programmer edit section *** (IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.DetailArrayOfСведения members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Сведения by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Сведения.
        /// </summary>
        public DetailArrayOfСведения(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Животные fЖивотные) : 
                base(typeof(Сведения), ((ICSSoft.STORMNET.DataObject)(fЖивотные)))
        {
        }
        
        public IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сведения this[int index]
        {
            get
            {
                return ((IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сведения)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сведения dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
