//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ТабличНомер as \'Таблич номер\'",
            "КодДолжности as \'Код должности\'",
            "Должность as \'Должность\'",
            "Должность.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должность.Наименование"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СотрудникиL", new string[] {
            "ТабличНомер as \'Таблич номер\'",
            "КодДолжности as \'Код должности\'",
            "Должность.Наименование as \'Наименование\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fТабличНомер;
        
        private int fКодДолжности;
        
        private IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Должность fДолжность;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// КодДолжности.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.КодДолжности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.КодДолжности CustomAttributes)
        public virtual int КодДолжности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.КодДолжности Get start)

                // *** End programmer edit section *** (Сотрудники.КодДолжности Get start)
                int result = this.fКодДолжности;
                // *** Start programmer edit section *** (Сотрудники.КодДолжности Get end)

                // *** End programmer edit section *** (Сотрудники.КодДолжности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.КодДолжности Set start)

                // *** End programmer edit section *** (Сотрудники.КодДолжности Set start)
                this.fКодДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.КодДолжности Set end)

                // *** End programmer edit section *** (Сотрудники.КодДолжности Set end)
            }
        }
        
        /// <summary>
        /// ТабличНомер.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ТабличНомер CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ТабличНомер CustomAttributes)
        public virtual int ТабличНомер
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ТабличНомер Get start)

                // *** End programmer edit section *** (Сотрудники.ТабличНомер Get start)
                int result = this.fТабличНомер;
                // *** Start programmer edit section *** (Сотрудники.ТабличНомер Get end)

                // *** End programmer edit section *** (Сотрудники.ТабличНомер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ТабличНомер Set start)

                // *** End programmer edit section *** (Сотрудники.ТабличНомер Set start)
                this.fТабличНомер = value;
                // *** Start programmer edit section *** (Сотрудники.ТабличНомер Set end)

                // *** End programmer edit section *** (Сотрудники.ТабличНомер Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должность CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Get start)

                // *** End programmer edit section *** (Сотрудники.Должность Get start)
                IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (Сотрудники.Должность Get end)

                // *** End programmer edit section *** (Сотрудники.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должность Set start)

                // *** End programmer edit section *** (Сотрудники.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (Сотрудники.Должность Set end)

                // *** End programmer edit section *** (Сотрудники.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Avtomatizaciya_ucheta_zayavok_v_IT_kompanii.Сотрудники));
                }
            }
        }
    }
}
